spring.application.name=FinaceAnomoly

spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
Gemini_key=${GEMINI_KEY}

spring.jpa.hibernate.ddl-auto=update
